#!/bin/bash
#SBATCH --job-name=barrnap
#SBATCH --mem=1G
#SBATCH --cpus-per-task=1
#SBATCH --time=01:00:00
#SBATCH --output=%x_%j.log
#SBATCH --array=1-96

# Check if input directory argument is provided
if [ $# -eq 0 ]; then
    echo "Error: No working directory provided"
    echo "Usage: sbatch $0 /path/to/workdir/primerless"
    echo "Example: sbatch $0 Lakes_day1/primerless"
    exit 1
fi

# Define directories
workdir="$1"
# Get the parent directory for output (Lakes_day1 instead of Lakes_day1/primerless)
parent_dir=$(dirname "$workdir")
input_pattern="${workdir}/*/rRNAs/cleaned_amplicon*.fasta"
output_base_dir="${parent_dir}/rRNA_genes"

echo "Working directory: ${workdir}"
echo "Parent directory: ${parent_dir}"
echo "Input pattern: ${input_pattern}"
echo "Output base dir: ${output_base_dir}"

# Get the filename for the current task
input_file=$(ls ${input_pattern} 2>/dev/null | sed -n "${SLURM_ARRAY_TASK_ID}p")
echo "File being processed: ${input_file}"

# Check if file exists
if [ ! -f "$input_file" ]; then
    echo "Error: No file found for array task ${SLURM_ARRAY_TASK_ID}"
    exit 1
fi

# Extract sample identifier from path
# From: <workdir>/<sample><dataset>/rRNAs/cleaned_amplicon*.fasta
sample_path=$(dirname $(dirname "$input_file"))
identifier=$(basename "$sample_path")

echo "Identifier: ${identifier}"

# Create output directory for this sample
sample_output_dir="${output_base_dir}/${identifier}"
mkdir -p "${sample_output_dir}"

#===============================#
# CHECK: Check for existing fasta index - error if found

input_fai="${input_file}.fai"
echo "=== Checking for existing FASTA index ==="

if [ -f "$input_fai" ]; then
    echo "✗ ERROR: Existing fasta index found at ${input_fai}"
    echo "Please remove all .fai files from input directories before running"
    exit 1
else
    echo "✓ No existing index found, proceeding"
fi

#===============================#
# run barrnap

# Activate conda environment
source activate barrnap

# Create temporary directory for barrnap output
temp_dir="${sample_output_dir}/barrnap_outs"
mkdir -p "${temp_dir}"

# Run barrnap
barrnap -k euk -t 1 --incseq \
    -o "${temp_dir}/${identifier}_euk.fa" \
    "${input_file}" > "${temp_dir}/${identifier}_euk.gff3"

echo "Barrnap completed for ${identifier}"

# Remove the fasta index created by barrnap
if [ -f "$input_fai" ]; then
    rm -f "$input_fai"
    echo "CORRECT: Barrnap-generated fasta index removed"
else
    echo "WARNING: No fasta index was generated by barrnap"
fi

#===============================#
# CHECK: did barrnap run correctly? Have we got the same number of hits in the gff3 and the fasta? 

# CHECK: FASTA sequences match between output file and GFF3 footer
fasta_output_count=$(grep -c "^>" "${temp_dir}/${identifier}_euk.fa" 2>/dev/null || echo 0)
# Extract FASTA section from GFF3 (everything after ##FASTA line)
gff_fasta_count=$(awk '/^##FASTA/{flag=1; next} flag && /^>/{count++} END{print count+0}' "${temp_dir}/${identifier}_euk.gff3")

echo "FASTA output file count: ${fasta_output_count}"
echo "FASTA in GFF3 count: ${gff_fasta_count}"

if [ "$fasta_output_count" -eq "$gff_fasta_count" ]; then
    echo "CORRECT: FASTA output matches GFF3 embedded sequences"
else
    echo "WARNING: FASTA output (${fasta_output_count}) != GFF3 FASTA (${gff_fasta_count})"
fi

#===============================#
# run step to reorganise outputs

conda deactivate && source activate seqkit

# Split the output by rRNA type (keep only 18S and 28S)
if [ -f "${temp_dir}/${identifier}_euk.fa" ]; then
    # Count sequences in original file by type
    count_18S_original=$(seqkit grep -r -p "18S_rRNA" "${temp_dir}/${identifier}_euk.fa" | grep -c "^>" || echo 0)
    count_28S_original=$(seqkit grep -r -p "28S_rRNA" "${temp_dir}/${identifier}_euk.fa" | grep -c "^>" || echo 0)
    
    # Use seqkit grep to extract by pattern in header
    seqkit grep -r -p "18S_rRNA" "${temp_dir}/${identifier}_euk.fa" > "${sample_output_dir}/${identifier}_18S.fa"
    seqkit grep -r -p "28S_rRNA" "${temp_dir}/${identifier}_euk.fa" > "${sample_output_dir}/${identifier}_28S.fa"
  
    # CHECK: Count sequences in split files
    count_18S_split=$(grep -c "^>" "${sample_output_dir}/${identifier}_18S.fa" 2>/dev/null || echo 0)
    count_28S_split=$(grep -c "^>" "${sample_output_dir}/${identifier}_28S.fa" 2>/dev/null || echo 0)
    
    echo "18S sequences - Original: ${count_18S_original}, Split: ${count_18S_split}"
    echo "28S sequences - Original: ${count_28S_original}, Split: ${count_28S_split}"
    
    if [ "$count_18S_original" -eq "$count_18S_split" ]; then
        echo "CORRECT: 18S sequence counts match"
    else
        echo "WARNING: 18S counts don't match (Original: ${count_18S_original}, Split: ${count_18S_split})"
    fi
    
    if [ "$count_28S_original" -eq "$count_28S_split" ]; then
        echo "CORRECT: 28S sequence counts match"
    else
        echo "WARNING: 28S counts don't match (Original: ${count_28S_original}, Split: ${count_28S_split})"
    fi
    
    # CHECK: Verify sequence content matches
    # Extract 18S from original and compare with split file
    seqkit grep -r -p "18S_rRNA" "${temp_dir}/${identifier}_euk.fa" | seqkit seq -w 0 | sort > "${temp_dir}/18S_original_sorted.fa"
    seqkit seq -w 0 "${sample_output_dir}/${identifier}_18S.fa" | sort > "${temp_dir}/18S_split_sorted.fa"
    
    if diff -q "${temp_dir}/18S_original_sorted.fa" "${temp_dir}/18S_split_sorted.fa" > /dev/null 2>&1; then
        echo "CORRECT: 18S sequence content identical"
    else
        echo "WARNING: 18S sequence content differs between original and split"
    fi
    
    # Extract 28S from original and compare with split file
    seqkit grep -r -p "28S_rRNA" "${temp_dir}/${identifier}_euk.fa" | seqkit seq -w 0 | sort > "${temp_dir}/28S_original_sorted.fa"
    seqkit seq -w 0 "${sample_output_dir}/${identifier}_28S.fa" | sort > "${temp_dir}/28S_split_sorted.fa"
    
    if diff -q "${temp_dir}/28S_original_sorted.fa" "${temp_dir}/28S_split_sorted.fa" > /dev/null 2>&1; then
        echo "CORRECT: 28S sequence content identical"
    else
        echo "WARNING: 28S sequence content differs between original and split"
    fi
    
    # Clean up temporary sorted files
    rm -f "${temp_dir}/18S_original_sorted.fa" "${temp_dir}/18S_split_sorted.fa"
    rm -f "${temp_dir}/28S_original_sorted.fa" "${temp_dir}/28S_split_sorted.fa"
    
else
    echo "ERROR: No barrnap output found for ${identifier}"
    exit 1
fi

echo "=== Processing completed for ${identifier} ==="