#!/bin/bash
#SBATCH --job-name=barrnap
#SBATCH --mem=1G
#SBATCH --cpus-per-task=1
#SBATCH --time=01:00:00
#SBATCH --output=%x_%j.log
#SBATCH --array=1-96

# Check if input directory argument is provided
if [ $# -eq 0 ]; then
    echo "Error: No working directory provided"
    echo "Usage: sbatch $0 /path/to/workdir/primerless"
    echo "Example: sbatch $0 Lakes_day1/primerless"
    exit 1
fi

# Define directories
workdir="$1"
# Get the parent directory for output (Lakes_day1 instead of Lakes_day1/primerless)
parent_dir=$(dirname "$workdir")
input_pattern="${workdir}/*/rRNAs/cleaned_amplicon*.fasta"
output_base_dir="${parent_dir}/rRNA_genes"

echo "Working directory: ${workdir}"
echo "Parent directory: ${parent_dir}"
echo "Input pattern: ${input_pattern}"
echo "Output base dir: ${output_base_dir}"

# Get the filename for the current task
input_file=$(ls ${input_pattern} 2>/dev/null | sed -n "${SLURM_ARRAY_TASK_ID}p")
echo "File being processed: ${input_file}"

# Check if file exists
if [ ! -f "$input_file" ]; then
    echo "Error: No file found for array task ${SLURM_ARRAY_TASK_ID}"
    exit 1
fi

# Extract sample identifier from path
# From: <workdir>/<sample><dataset>/rRNAs/cleaned_amplicon*.fasta
sample_path=$(dirname $(dirname "$input_file"))
identifier=$(basename "$sample_path")

echo "Identifier: ${identifier}"

# Create output directory for this sample
sample_output_dir="${output_base_dir}/${identifier}"
mkdir -p "${sample_output_dir}"

#===============================#
# CRUCIAL CHECK: Check for existing fasta index - error if found

input_fai="${input_file}.fai"
echo "=== Checking for existing FASTA index ==="

if [ -f "$input_fai" ]; then
    echo "✗ ERROR: Existing fasta index found at ${input_fai}"
    echo "Please remove all .fai files from input directories before running"
    exit 1
else
    echo "✓ No existing index found, proceeding"
fi

#===============================#
# run barrnap

# Activate conda environment
source activate barrnap

# Create temporary directory for barrnap output
temp_dir="${sample_output_dir}/barrnap_outs"
mkdir -p "${temp_dir}"

# Run barrnap
barrnap -k euk -t 1 --incseq \
    -o "${temp_dir}/${identifier}_euk.fa" \
    "${input_file}" > "${temp_dir}/${identifier}_euk.gff3"

echo "Barrnap completed for ${identifier}"

# Remove the fasta index created by barrnap
if [ -f "$input_fai" ]; then
    rm -f "$input_fai"
    echo "✓ Barrnap-generated fasta index removed"
else
    echo "⚠ WARNING: No fasta index was generated by barrnap"
fi

#===============================#
# run step to reorganise outputs, based on seqkit

conda deactivate && source activate seqkit

# Split the output by rRNA type (keep only 18S and 28S)
if [ -f "${temp_dir}/${identifier}_euk.fa" ]; then
    
    # Count sequences in original file by type
    count_18S_original=$(seqkit grep -r -p "18S_rRNA" "${temp_dir}/${identifier}_euk.fa" | grep -c "^>" || echo 0)
    count_28S_original=$(seqkit grep -r -p "28S_rRNA" "${temp_dir}/${identifier}_euk.fa" | grep -c "^>" || echo 0)
    
    echo "Found ${count_18S_original} 18S sequences and ${count_28S_original} 28S sequences"
    
    # Use seqkit grep to extract by pattern in header
    seqkit grep -r -p "18S_rRNA" "${temp_dir}/${identifier}_euk.fa" > "${sample_output_dir}/${identifier}_18S.fa"
    seqkit grep -r -p "28S_rRNA" "${temp_dir}/${identifier}_euk.fa" > "${sample_output_dir}/${identifier}_28S.fa"
    
    # Verify output files were created
    if [ -f "${sample_output_dir}/${identifier}_18S.fa" ]; then
        echo "18S file created: ${sample_output_dir}/${identifier}_18S.fa"
    else
        echo "WARNING: 18S file not created, somethign is wrong!"
    fi
    
    if [ -f "${sample_output_dir}/${identifier}_28S.fa" ]; then
        echo "28S file created: ${sample_output_dir}/${identifier}_28S.fa"
    else
        echo "WARNING: 28S file not created, somethign is wrong!"
    fi
    
else
    echo "!!! ERROR !!! No barrnap output found for ${identifier} at all, something is wrong!"
    exit 1
fi

echo "=== Processing completed for ${identifier} ==="